# Form implementation generated from reading ui file 'Detail_page.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1527, 851)
        Form.setStyleSheet("/* Main Application Background */\n"
"QWidget {\n"
"    background-color: #2D2A2E; /* Dark gray background */\n"
"    color: #FFD866; /* Golden text */\n"
"    font-family: \"Consolas\", \"Monospace\";\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"/* Buttons */\n"
"QPushButton {\n"
"    background-color: #FFD866; /* Golden hue */\n"
"    color: #2D2A2E; /* Dark gray text for contrast */\n"
"    border: 1px solid #FFD866; /* Golden border */\n"
"    border-radius: 4px;\n"
"    padding: 5px 10px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #FFB52E; /* Slightly darker golden hue on hover */\n"
"    border: 1px solid #FFB52E;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #FF9F00; /* Even darker golden hue when pressed */\n"
"    border: 1px solid #FF9F00;\n"
"}\n"
"\n"
"/* Text Inputs (QLineEdit, QTextEdit) */\n"
"QLineEdit, QTextEdit {\n"
"    background-color: #3E3D40; /* Dark gray */\n"
"    color: #FFD866; /* Golden text */\n"
"    border: 1px solid #5A595C; /* Slightly lighter gray border */\n"
"    border-radius: 4px;\n"
"    padding: 5px;\n"
"    font-size: 14px;\n"
"}\n"
"/* Vertical Sliders (matching horizontal style) */\n"
"QSlider::groove:vertical {\n"
"    background-color: #5A595C;\n"
"    width: 6px;  /* Changed from height for vertical */\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QSlider::handle:vertical {\n"
"    background-color: #FFD866;\n"
"    width: 16px;  /* Maintain same size as horizontal */\n"
"    height: 16px;\n"
"    margin: 0 -5px;  /* Adjusted for vertical orientation */\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"/* Optional: Add these if you want to style tick marks */\n"
"QSlider::sub-page:vertical {\n"
"    background-color: #FFD866;\n"
"}\n"
"\n"
"QSlider::add-page:vertical {\n"
"    background-color: #5A595C;\n"
"}\n"
"\n"
"QLineEdit:focus, QTextEdit:focus {\n"
"    border: 1px solid #FFD866; /* Yellow border on focus */\n"
"}\n"
"\n"
"/* Labels */\n"
"QLabel {\n"
"    color: #FFD866; /* Golden text */\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"/* Scrollbars */\n"
"QScrollBar:vertical, QScrollBar:horizontal {\n"
"    background-color: #2D2A2E; /* Dark gray */\n"
"}\n"
"\n"
"QScrollBar::handle:vertical, QScrollBar::handle:horizontal {\n"
"    background-color: #5A595C; /* Lighter gray */\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical,\n"
"QScrollBar::add-line:horizontal, QScrollBar::sub-line:horizontal,\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical,\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"    background: none;\n"
"}\n"
"\n"
"/* Menus */\n"
"QMenuBar {\n"
"    background-color: #2D2A2E; /* Dark gray */\n"
"    color: #FFD866; /* Golden text */\n"
"}\n"
"\n"
"QMenuBar::item {\n"
"    background-color: transparent;\n"
"    padding: 5px 10px;\n"
"}\n"
"\n"
"QMenuBar::item:selected {\n"
"    background-color: #5A595C; /* Lighter gray */\n"
"}\n"
"\n"
"QMenu {\n"
"    background-color: #3E3D40; /* Dark gray */\n"
"    color: #FFD866; /* Golden text */\n"
"    border: 1px solid #5A595C;\n"
"}\n"
"\n"
"QMenu::item {\n"
"    padding: 5px 20px;\n"
"}\n"
"\n"
"QMenu::item:selected {\n"
"    background-color: #5A595C;\n"
"}\n"
"\n"
"/* Tabs */\n"
"QTabWidget::pane {\n"
"    border: 1px solid #5A595C;\n"
"    background-color: #3E3D40;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    background-color: #3E3D40;\n"
"    color: #FFD866; /* Golden text */\n"
"    padding: 8px 12px;\n"
"    border: 1px solid #5A595C;\n"
"    border-bottom: none;\n"
"    border-top-left-radius: 4px;\n"
"    border-top-right-radius: 4px;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background-color: #2D2A2E;\n"
"    border-color: #5A595C;\n"
"}\n"
"\n"
"QTabBar::tab:hover {\n"
"    background-color: #FFD866;\n"
"    color: #2D2A2E;\n"
"}\n"
"\n"
"/* Sliders */\n"
"QSlider::groove:horizontal {\n"
"    background-color: #5A595C;\n"
"    height: 6px;\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background-color: #FFD866;\n"
"    width: 16px;\n"
"    height: 16px;\n"
"    margin: -5px 0;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"/* Progress Bars */\n"
"QProgressBar {\n"
"    background-color: #3E3D40;\n"
"    border: 1px solid #5A595C;\n"
"    border-radius: 4px;\n"
"    text-align: center;\n"
"    color: #FFD866; /* Golden text */\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: #FFD866;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"/* Checkboxes and Radio Buttons */\n"
"QCheckBox, QRadioButton {\n"
"    color: #FFD866; /* Golden text */\n"
"    spacing: 5px;\n"
"}\n"
"\n"
"QCheckBox::indicator, QRadioButton::indicator {\n"
"    width: 16px;\n"
"    height: 16px;\n"
"    border: 1px solid #5A595C;\n"
"    border-radius: 3px;\n"
"    background-color: #3E3D40;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked, QRadioButton::indicator:checked {\n"
"    background-color: #FFD866;\n"
"    border: 1px solid #FFD866;\n"
"}\n"
"\n"
"/* Group Boxes */\n"
"QGroupBox {\n"
"    border: 1px solid #5A595C;\n"
"    border-radius: 4px;\n"
"    margin-top: 10px;\n"
"    padding-top: 10px;\n"
"    color: #FFD866; /* Golden text */\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left;\n"
"    padding: 0 5px;\n"
"    background-color: #2D2A2E;\n"
"}\n"
"")
        self.horizontalSlider = QtWidgets.QSlider(parent=Form)
        self.horizontalSlider.setGeometry(QtCore.QRect(20, 600, 160, 41))
        self.horizontalSlider.setMinimum(1)
        self.horizontalSlider.setMaximum(3)
        self.horizontalSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.frame = QtWidgets.QFrame(parent=Form)
        self.frame.setGeometry(QtCore.QRect(80, 30, 1361, 481))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label_11 = QtWidgets.QLabel(parent=self.frame)
        self.label_11.setGeometry(QtCore.QRect(0, 0, 55, 16))
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(24, 550, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Consolas,Monospace")
        font.setPointSize(-1)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setGeometry(QtCore.QRect(24, 660, 161, 21))
        font = QtGui.QFont()
        font.setFamily("Consolas,Monospace")
        font.setPointSize(-1)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalSlider_2 = QtWidgets.QSlider(parent=Form)
        self.horizontalSlider_2.setGeometry(QtCore.QRect(20, 710, 160, 41))
        self.horizontalSlider_2.setMaximum(100)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.label_3 = QtWidgets.QLabel(parent=Form)
        self.label_3.setGeometry(QtCore.QRect(520, 550, 301, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas,Monospace")
        font.setPointSize(-1)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=Form)
        self.label_4.setGeometry(QtCore.QRect(730, 610, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Consolas,Monospace")
        font.setPointSize(-1)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lineEdit = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit.setGeometry(QtCore.QRect(750, 650, 113, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(470, 650, 113, 22))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_5 = QtWidgets.QLabel(parent=Form)
        self.label_5.setGeometry(QtCore.QRect(450, 610, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Consolas,Monospace")
        font.setPointSize(-1)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=Form)
        self.label_6.setGeometry(QtCore.QRect(141, 10, 1251, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas,Monospace")
        font.setPointSize(-1)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.pushButton_2 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_2.setGeometry(QtCore.QRect(480, 700, 401, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_7 = QtWidgets.QLabel(parent=Form)
        self.label_7.setGeometry(QtCore.QRect(1290, 550, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas,Monospace")
        font.setPointSize(-1)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.pushButton_3 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_3.setGeometry(QtCore.QRect(1300, 610, 151, 28))
        self.pushButton_3.setObjectName("pushButton_3")
        self.groupBox = QtWidgets.QGroupBox(parent=Form)
        self.groupBox.setGeometry(QtCore.QRect(970, 550, 271, 191))
        self.groupBox.setObjectName("groupBox")
        self.checkBox = QtWidgets.QCheckBox(parent=self.groupBox)
        self.checkBox.setGeometry(QtCore.QRect(10, 30, 201, 20))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(parent=self.groupBox)
        self.checkBox_2.setGeometry(QtCore.QRect(10, 90, 201, 20))
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(parent=self.groupBox)
        self.checkBox_3.setGeometry(QtCore.QRect(10, 60, 261, 20))
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(parent=self.groupBox)
        self.checkBox_4.setGeometry(QtCore.QRect(10, 120, 201, 20))
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_5 = QtWidgets.QCheckBox(parent=self.groupBox)
        self.checkBox_5.setGeometry(QtCore.QRect(10, 150, 241, 20))
        self.checkBox_5.setObjectName("checkBox_5")
        self.label_9 = QtWidgets.QLabel(parent=Form)
        self.label_9.setGeometry(QtCore.QRect(200, 550, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Consolas,Monospace")
        font.setPointSize(-1)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(parent=Form)
        self.label_10.setGeometry(QtCore.QRect(340, 550, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Consolas,Monospace")
        font.setPointSize(-1)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.verticalSlider = QtWidgets.QSlider(parent=Form)
        self.verticalSlider.setGeometry(QtCore.QRect(240, 590, 22, 160))
        self.verticalSlider.setMinimum(3)
        self.verticalSlider.setMaximum(31)
        self.verticalSlider.setSliderPosition(31)
        self.verticalSlider.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.verticalSlider.setObjectName("verticalSlider")
        self.verticalSlider_2 = QtWidgets.QSlider(parent=Form)
        self.verticalSlider_2.setGeometry(QtCore.QRect(380, 590, 22, 160))
        self.verticalSlider_2.setPageStep(100)
        self.verticalSlider_2.setSliderPosition(99)
        self.verticalSlider_2.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.verticalSlider_2.setObjectName("verticalSlider_2")
        self.dial = QtWidgets.QDial(parent=Form)
        self.dial.setGeometry(QtCore.QRect(1350, 710, 50, 64))
        self.dial.setMaximum(255)
        self.dial.setObjectName("dial")
        self.label_8 = QtWidgets.QLabel(parent=Form)
        self.label_8.setGeometry(QtCore.QRect(1290, 670, 181, 21))
        font = QtGui.QFont()
        font.setFamily("Consolas,Monospace")
        font.setPointSize(-1)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.line = QtWidgets.QFrame(parent=Form)
        self.line.setGeometry(QtCore.QRect(0, 540, 16, 261))
        self.line.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(parent=Form)
        self.line_2.setGeometry(QtCore.QRect(20, 530, 1481, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(parent=Form)
        self.line_3.setGeometry(QtCore.QRect(10, 790, 1481, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(parent=Form)
        self.line_4.setGeometry(QtCore.QRect(1490, 540, 16, 261))
        self.line_4.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_4.setObjectName("line_4")
        self.pushButton_4 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_4.setGeometry(QtCore.QRect(580, 750, 151, 28))
        self.pushButton_4.setObjectName("pushButton_4")
        self.toolButton = QtWidgets.QToolButton(parent=Form)
        self.toolButton.setGeometry(QtCore.QRect(10, 10, 81, 22))
        self.toolButton.setObjectName("toolButton")
        self.progressBar = QtWidgets.QProgressBar(parent=Form)
        self.progressBar.setGeometry(QtCore.QRect(1080, 750, 118, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.label_12 = QtWidgets.QLabel(parent=Form)
        self.label_12.setGeometry(QtCore.QRect(990, 750, 81, 20))
        font = QtGui.QFont()
        font.setFamily("Consolas,Monospace")
        font.setPointSize(-1)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "      Gamma"))
        self.label_2.setText(_translate("Form", "Laplacian Sharpening "))
        self.label_3.setText(_translate("Form", "         Contrast Stretching"))
        self.label_4.setText(_translate("Form", "       new max"))
        self.label_5.setText(_translate("Form", "      new min"))
        self.label_6.setText(_translate("Form", "                                                             Xray"))
        self.pushButton_2.setText(_translate("Form", "Apply Contrast Stretching"))
        self.label_7.setText(_translate("Form", "  Inverse Of Image"))
        self.pushButton_3.setText(_translate("Form", "Apply"))
        self.groupBox.setTitle(_translate("Form", "Histogram Operations"))
        self.checkBox.setText(_translate("Form", "Histogram Equalization"))
        self.checkBox_2.setText(_translate("Form", "Contrast Limited AHE"))
        self.checkBox_3.setText(_translate("Form", "Adaptive Limited Equalization"))
        self.checkBox_4.setText(_translate("Form", "Histogram Shifting"))
        self.checkBox_5.setText(_translate("Form", "Quantile-Based Equalization"))
        self.label_9.setText(_translate("Form", "Gaussian Blur"))
        self.label_10.setText(_translate("Form", "  Log Transform"))
        self.label_8.setText(_translate("Form", "  Image Thresholding"))
        self.pushButton_4.setText(_translate("Form", "Save Image"))
        self.toolButton.setText(_translate("Form", "Back"))
        self.label_12.setText(_translate("Form", "progress:"))
