# Form implementation generated from reading ui file 'Main_Page_ui.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1521, 851)
        MainWindow.setStyleSheet("""/* Main Application Background */
QWidget {
    background-color: #2D2A2E; /* Dark gray background */
    color: #FFD866; /* Golden text */
    font-family: "Consolas", "Monospace";
    font-size: 14px;
}

/* Buttons */
QPushButton {
    background-color: #FFD866; /* Golden hue */
    color: #2D2A2E; /* Dark gray text for contrast */
    border: 1px solid #FFD866; /* Golden border */
    border-radius: 4px;
    padding: 5px 10px;
    font-size: 14px;
}

QPushButton:hover {
    background-color: #FFB52E; /* Slightly darker golden hue on hover */
    border: 1px solid #FFB52E;
}

QPushButton:pressed {
    background-color: #FF9F00; /* Even darker golden hue when pressed */
    border: 1px solid #FF9F00;
}

/* Text Inputs (QLineEdit, QTextEdit) */
QLineEdit, QTextEdit {
    background-color: #3E3D40; /* Dark gray */
    color: #FFD866; /* Golden text */
    border: 1px solid #5A595C; /* Slightly lighter gray border */
    border-radius: 4px;
    padding: 5px;
    font-size: 14px;
}
/* Vertical Sliders (matching horizontal style) */
QSlider::groove:vertical {
    background-color: #5A595C;
    width: 6px;  /* Changed from height for vertical */
    border-radius: 3px;
}

QSlider::handle:vertical {
    background-color: #FFD866;
    width: 16px;  /* Maintain same size as horizontal */
    height: 16px;
    margin: 0 -5px;  /* Adjusted for vertical orientation */
    border-radius: 8px;
}

/* Optional: Add these if you want to style tick marks */
QSlider::sub-page:vertical {
    background-color: #FFD866;
}

QSlider::add-page:vertical {
    background-color: #5A595C;
}

QLineEdit:focus, QTextEdit:focus {
    border: 1px solid #FFD866; /* Yellow border on focus */
}

/* Labels */
QLabel {
    color: #FFD866; /* Golden text */
    font-size: 14px;
}

/* Scrollbars */
QScrollBar:vertical, QScrollBar:horizontal {
    background-color: #2D2A2E; /* Dark gray */
}

QScrollBar::handle:vertical, QScrollBar::handle:horizontal {
    background-color: #5A595C; /* Lighter gray */
    border-radius: 6px;
}

QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical,
QScrollBar::add-line:horizontal, QScrollBar::sub-line:horizontal,
QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical,
QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {
    background: none;
}

/* Menus */
QMenuBar {
    background-color: #2D2A2E; /* Dark gray */
    color: #FFD866; /* Golden text */
}

QMenuBar::item {
    background-color: transparent;
    padding: 5px 10px;
}

QMenuBar::item:selected {
    background-color: #5A595C; /* Lighter gray */
}

QMenu {
    background-color: #3E3D40; /* Dark gray */
    color: #FFD866; /* Golden text */
    border: 1px solid #5A595C;
}

QMenu::item {
    padding: 5px 20px;
}

QMenu::item:selected {
    background-color: #5A595C;
}

/* Tabs */
QTabWidget::pane {
    border: 1px solid #5A595C;
    background-color: #3E3D40;
}

QTabBar::tab {
    background-color: #3E3D40;
    color: #FFD866; /* Golden text */
    padding: 8px 12px;
    border: 1px solid #5A595C;
    border-bottom: none;
    border-top-left-radius: 4px;
    border-top-right-radius: 4px;
}

QTabBar::tab:selected {
    background-color: #2D2A2E;
    border-color: #5A595C;
}

QTabBar::tab:hover {
    background-color: #FFD866;
    color: #2D2A2E;
}

/* Sliders */
QSlider::groove:horizontal {
    background-color: #5A595C;
    height: 6px;
    border-radius: 3px;
}

QSlider::handle:horizontal {
    background-color: #FFD866;
    width: 16px;
    height: 16px;
    margin: -5px 0;
    border-radius: 8px;
}

/* Progress Bars */
QProgressBar {
    background-color: #3E3D40;
    border: 1px solid #5A595C;
    border-radius: 4px;
    text-align: center;
    color: #FFD866; /* Golden text */
}

QProgressBar::chunk {
    background-color: #FFD866;
    border-radius: 4px;
}

/* Checkboxes and Radio Buttons */
QCheckBox, QRadioButton {
    color: #FFD866; /* Golden text */
    spacing: 5px;
}

QCheckBox::indicator, QRadioButton::indicator {
    width: 16px;
    height: 16px;
    border: 1px solid #5A595C;
    border-radius: 3px;
    background-color: #3E3D40;
}

QCheckBox::indicator:checked, QRadioButton::indicator:checked {
    background-color: #FFD866;
    border: 1px solid #FFD866;
}

/* Group Boxes */
QGroupBox {
    border: 1px solid #5A595C;
    border-radius: 4px;
    margin-top: 10px;
    padding-top: 10px;
    color: #FFD866; /* Golden text */
}

QGroupBox::title {
    subcontrol-origin: margin;
    subcontrol-position: top left;
    padding: 0 5px;
    background-color: #2D2A2E;
}

""")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(317, 80, 891, 491))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setGeometry(QtCore.QRect(430, 230, 55, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(342, 39, 831, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas,Monospace")
        font.setPointSize(-1)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.listView = QtWidgets.QListView(parent=self.centralwidget)
        self.listView.setGeometry(QtCore.QRect(1220, 140, 281, 421))
        self.listView.setObjectName("listView")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(1232, 90, 241, 31))
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(290, 600, 921, 41))
        self.pushButton.setObjectName("pushButton")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(50, 90, 211, 31))
        self.label_4.setObjectName("label_4")
        self.listView_2 = QtWidgets.QListView(parent=self.centralwidget)
        self.listView_2.setGeometry(QtCore.QRect(20, 140, 281, 421))
        self.listView_2.setObjectName("listView_2")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(40, 600, 181, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(1280, 600, 181, 41))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(290, 751, 921, 41))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(290, 680, 921, 41))
        self.pushButton_5.setObjectName("pushButton_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1521, 28))
        self.menubar.setObjectName("menubar")
        self.menufile = QtWidgets.QMenu(parent=self.menubar)
        self.menufile.setObjectName("menufile")
        self.menusettings = QtWidgets.QMenu(parent=self.menubar)
        self.menusettings.setObjectName("menusettings")
        self.menuabout = QtWidgets.QMenu(parent=self.menubar)
        self.menuabout.setObjectName("menuabout")
        self.menulicense = QtWidgets.QMenu(parent=self.menubar)
        self.menulicense.setObjectName("menulicense")
        MainWindow.setMenuBar(self.menubar)
        self.menubar.addAction(self.menufile.menuAction())
        self.menubar.addAction(self.menusettings.menuAction())
        self.menubar.addAction(self.menuabout.menuAction())
        self.menubar.addAction(self.menulicense.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "image"))
        self.label_2.setText(_translate("MainWindow", "                                     Upload Your Image Here"))
        self.label_3.setText(_translate("MainWindow", "          Treatment"))
        self.pushButton.setText(_translate("MainWindow", "Upload Your Image"))
        self.label_4.setText(_translate("MainWindow", "     Causes Of Disease"))
        self.pushButton_2.setText(_translate("MainWindow", "Save "))
        self.pushButton_3.setText(_translate("MainWindow", "Save "))
        self.pushButton_4.setText(_translate("MainWindow", "Save new Image"))
        self.pushButton_5.setText(_translate("MainWindow", "Details Of Image"))
        self.menufile.setTitle(_translate("MainWindow", "file"))
        self.menusettings.setTitle(_translate("MainWindow", "settings"))
        self.menuabout.setTitle(_translate("MainWindow", "about"))
        self.menulicense.setTitle(_translate("MainWindow", "license"))
