# Form implementation generated from reading ui file 'Main_Page_ui.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1521, 851)
        MainWindow.setStyleSheet("/* Main Application Background */\n"
"QWidget {\n"
"    background-color: #2D2A2E; /* Dark gray background */\n"
"    color: #FFD866; /* Golden text */\n"
"    font-family: \"Consolas\", \"Monospace\";\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"/* Buttons */\n"
"QPushButton {\n"
"    background-color: #FFD866; /* Golden hue */\n"
"    color: #2D2A2E; /* Dark gray text for contrast */\n"
"    border: 1px solid #FFD866; /* Golden border */\n"
"    border-radius: 4px;\n"
"    padding: 5px 10px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #FFB52E; /* Slightly darker golden hue on hover */\n"
"    border: 1px solid #FFB52E;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #FF9F00; /* Even darker golden hue when pressed */\n"
"    border: 1px solid #FF9F00;\n"
"}\n"
"\n"
"/* Text Inputs (QLineEdit, QTextEdit) */\n"
"QLineEdit, QTextEdit {\n"
"    background-color: #3E3D40; /* Dark gray */\n"
"    color: #FFD866; /* Golden text */\n"
"    border: 1px solid #5A595C; /* Slightly lighter gray border */\n"
"    border-radius: 4px;\n"
"    padding: 5px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QLineEdit:focus, QTextEdit:focus {\n"
"    border: 1px solid #FFD866; /* Yellow border on focus */\n"
"}\n"
"\n"
"/* Labels */\n"
"QLabel {\n"
"    color: #FFD866; /* Golden text */\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"/* Scrollbars */\n"
"QScrollBar:vertical, QScrollBar:horizontal {\n"
"    background-color: #2D2A2E; /* Dark gray */\n"
"}\n"
"\n"
"QScrollBar::handle:vertical, QScrollBar::handle:horizontal {\n"
"    background-color: #5A595C; /* Lighter gray */\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical,\n"
"QScrollBar::add-line:horizontal, QScrollBar::sub-line:horizontal,\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical,\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"    background: none;\n"
"}\n"
"\n"
"/* Menus */\n"
"QMenuBar {\n"
"    background-color: #2D2A2E; /* Dark gray */\n"
"    color: #FFD866; /* Golden text */\n"
"}\n"
"\n"
"QMenuBar::item {\n"
"    background-color: transparent;\n"
"    padding: 5px 10px;\n"
"}\n"
"\n"
"QMenuBar::item:selected {\n"
"    background-color: #5A595C; /* Lighter gray */\n"
"}\n"
"\n"
"QMenu {\n"
"    background-color: #3E3D40; /* Dark gray */\n"
"    color: #FFD866; /* Golden text */\n"
"    border: 1px solid #5A595C;\n"
"}\n"
"\n"
"QMenu::item {\n"
"    padding: 5px 20px;\n"
"}\n"
"\n"
"QMenu::item:selected {\n"
"    background-color: #5A595C;\n"
"}\n"
"\n"
"/* Tabs */\n"
"QTabWidget::pane {\n"
"    border: 1px solid #5A595C;\n"
"    background-color: #3E3D40;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    background-color: #3E3D40;\n"
"    color: #FFD866; /* Golden text */\n"
"    padding: 8px 12px;\n"
"    border: 1px solid #5A595C;\n"
"    border-bottom: none;\n"
"    border-top-left-radius: 4px;\n"
"    border-top-right-radius: 4px;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background-color: #2D2A2E;\n"
"    border-color: #5A595C;\n"
"}\n"
"\n"
"QTabBar::tab:hover {\n"
"    background-color: #FFD866;\n"
"    color: #2D2A2E;\n"
"}\n"
"\n"
"/* Sliders */\n"
"QSlider::groove:horizontal {\n"
"    background-color: #5A595C;\n"
"    height: 6px;\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background-color: #FFD866;\n"
"    width: 16px;\n"
"    height: 16px;\n"
"    margin: -5px 0;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"/* Progress Bars */\n"
"QProgressBar {\n"
"    background-color: #3E3D40;\n"
"    border: 1px solid #5A595C;\n"
"    border-radius: 4px;\n"
"    text-align: center;\n"
"    color: #FFD866; /* Golden text */\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: #FFD866;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"/* Checkboxes and Radio Buttons */\n"
"QCheckBox, QRadioButton {\n"
"    color: #FFD866; /* Golden text */\n"
"    spacing: 5px;\n"
"}\n"
"\n"
"QCheckBox::indicator, QRadioButton::indicator {\n"
"    width: 16px;\n"
"    height: 16px;\n"
"    border: 1px solid #5A595C;\n"
"    border-radius: 3px;\n"
"    background-color: #3E3D40;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked, QRadioButton::indicator:checked {\n"
"    background-color: #FFD866;\n"
"    border: 1px solid #FFD866;\n"
"}\n"
"\n"
"/* Group Boxes */\n"
"QGroupBox {\n"
"    border: 1px solid #5A595C;\n"
"    border-radius: 4px;\n"
"    margin-top: 10px;\n"
"    padding-top: 10px;\n"
"    color: #FFD866; /* Golden text */\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left;\n"
"    padding: 0 5px;\n"
"    background-color: #2D2A2E;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(317, 80, 891, 491))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setGeometry(QtCore.QRect(430, 230, 55, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(342, 39, 831, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas,Monospace")
        font.setPointSize(-1)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.listView = QtWidgets.QListView(parent=self.centralwidget)
        self.listView.setGeometry(QtCore.QRect(1220, 140, 281, 421))
        self.listView.setObjectName("listView")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(1232, 90, 241, 31))
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(290, 600, 921, 41))
        self.pushButton.setObjectName("pushButton")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(50, 90, 211, 31))
        self.label_4.setObjectName("label_4")
        self.listView_2 = QtWidgets.QListView(parent=self.centralwidget)
        self.listView_2.setGeometry(QtCore.QRect(20, 140, 281, 421))
        self.listView_2.setObjectName("listView_2")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(40, 600, 181, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(1280, 600, 181, 41))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(290, 751, 921, 41))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(290, 680, 921, 41))
        self.pushButton_5.setObjectName("pushButton_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1521, 28))
        self.menubar.setObjectName("menubar")
        self.menufile = QtWidgets.QMenu(parent=self.menubar)
        self.menufile.setObjectName("menufile")
        self.menusettings = QtWidgets.QMenu(parent=self.menubar)
        self.menusettings.setObjectName("menusettings")
        self.menuabout = QtWidgets.QMenu(parent=self.menubar)
        self.menuabout.setObjectName("menuabout")
        self.menulicense = QtWidgets.QMenu(parent=self.menubar)
        self.menulicense.setObjectName("menulicense")
        MainWindow.setMenuBar(self.menubar)
        self.menubar.addAction(self.menufile.menuAction())
        self.menubar.addAction(self.menusettings.menuAction())
        self.menubar.addAction(self.menuabout.menuAction())
        self.menubar.addAction(self.menulicense.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "image"))
        self.label_2.setText(_translate("MainWindow", "                                     Upload Your Image Here"))
        self.label_3.setText(_translate("MainWindow", "          Treatment"))
        self.pushButton.setText(_translate("MainWindow", "Upload Your Image"))
        self.label_4.setText(_translate("MainWindow", "     Causes Of Disease"))
        self.pushButton_2.setText(_translate("MainWindow", "Save "))
        self.pushButton_3.setText(_translate("MainWindow", "Save "))
        self.pushButton_4.setText(_translate("MainWindow", "Save new Image"))
        self.pushButton_5.setText(_translate("MainWindow", "Details Of Image"))
        self.menufile.setTitle(_translate("MainWindow", "file"))
        self.menusettings.setTitle(_translate("MainWindow", "settings"))
        self.menuabout.setTitle(_translate("MainWindow", "about"))
        self.menulicense.setTitle(_translate("MainWindow", "license"))
